### ISSUE TITLE
First release for Device Swap v0.1

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceSwap#20]
**Problem description**
Deliver first release for Device Swap API.

cc: @jgarciahospital 

**Expected action**
In my understanding of the release process (from [here](https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14559630/API+Release+Process#API-release-numbering)) we can craft a first release r1.1 The version of the API will be v0.1.0-rc

to be check with @camaraproject/release-management_codeowners @hdamker 

**Additional context**
This will be done only when all other relevant issue are solved

**Comment by jgarciahospital** [comment]
As my understanding, version 0.1.0 (not RC) could also be launched right? It is, a version out of the meta-release process, that follows the commonalities and ICM of the previous meta and that, in next meta, will be updated and included officially.

**Comment by bigludo7** [comment]
This is one of my interrogation Jorge (and as indicated in my issue linked to the [page](https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14559630/API+Release+Process#API-release-numbering))  - Do we need to go thru a rc or can we go straight to 0.1.0?

Perhaps @tanjadegroot can help us ;)

**Comment by hdamker** [comment]
@jgarciahospital @bigludo7 the difference between v0.1.0-rc.1 and v0.1.0 is the difference between a pre-release and a public release of an initial version. 

But more important: each version and especially public release has certain prerequisites to fulfil, which you find in https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/API-Readiness-Checklist.md 

Looking on the repository and seeing that there are no test definitions yet, you would be currently able to have a release with v0.1.0-alpha.1. Already a release candidate has the mandatory prerequisite of basic API test cases & documentation defined. Otherwise it is not possible to validate the pre-released API definition in a lab/test implementation.

After you have test definitions it would be your decision if you want to skip the rc phase. You can do that if you are confident that there won't be bugs found during implementation. Even the smallest bug in the definition with a correction which is not backward compatible with the public initial 0.1.0 will require to continue with 0.2.0-*. With a release candidate which is used by your dev team you have the chance to continue with a second release candidate and/or correct it before the public release.

**Comment by hdamker** [comment]
> This will be done only when all other relevant issue are solved

In addition to my previous comment I propose to add the creation of basic test definitions to the relevant issues ;-)

**Comment by bigludo7** [comment]
Thanks @hdamker this is clear.
