### ISSUE TITLE
Discuss API Design

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceSwap#6]
**Problem description**
Potentially Device Swap API could provided 2 distinct information:

-  Request last Device Swap date (_When was the last device swap for the mobile line identified by the phone number +123456799?_)
- Check last Device swap by providing a delay (_Does we had a device swap for the last 240 hours for the mobile line identified by the phone number +123456799?_)

In order to move forward on the API design we should discuss on following questions

1. Are we sharing same expectations of the API?
2. Are we considering this information as independent one from the other ? We can have different privacy requirement, different way to commercialize it. Technical implementation feasibility should be considered.
3. How multi-SIM can affect this design?  

**Possible evolution**

**Alternative solution**

**Additional context**

**Comment by jgarciahospital** [comment]
> Are we sharing same expectations of the API?

Totally aligned on this perspective.

> Are we considering this information as independent one from the other ? We can have different privacy requirement, different way to commercialize it. Technical implementation feasibility should be considered.

For aligning as much as posible with Sim Swap, I'd tend to think that same kind of information is shared (date) and only difference may appear based on the age of the info that can be provided. If both endpoints consider the same kind of data age limitation (maxAge maximum value equal to the retrieve date maximum age), both endpoints should be considered as common and it will mostly be up to the developer to choose the best mechanism for retrieving the information.

> How multi-SIM can affect this design?

When a multi-SIM subscription is in place, more than one IMEI is associated to the same MSISDN. It is, depending on which device is active/connected, the record of IMEI associated tot he MSISDN will change time to time, sometimes more than one time per day/hour. Therefore, the device swap events will be triggered continuously and no valid information will be provided, since the event only represents that the user is activating one of his already existing devices.

Proposal is to only consider new devices as a valid device swap event, e.g. establishing a margin of 1 or several months in which a device can be used in the same MSISDN without considering it a device Swap event, as no valuable information for the API consumers.

**Comment by bigludo7** [comment]
For Multi-SIM please provide comment on the discussion #10

**Comment by bigludo7** [comment]
Hello @krishvenkatachalam 
May I ask you to provide feedback on the topic from MTN.
We should close on the topic of one or 2 yaml.
Thanks
cc: @wwAMRA

**Comment by bigludo7** [comment]
Hello @krishvenkatachalam , @wwAMRA 
Any update?
